all:    # группа по умолчанию
  children:     # указываем, что это вложенные хосты
    geek:     # задаём имя группы, может быть любым
      hosts: #
        Localhost:  # указываем ip или FQDN
        172.16.234.10:  # это объекты и после них надо делать двоеточие!!!
          ansible_user: "geek"

# Другой пример
all:
  children:
    geek:
      hosts:
        localhost:
    prodgeek:
      hosts:
        194.58.104.69: # тут должен быть ваш сервер
          ansible_user: root