all:    # группа по умолчанию
  children:     # указываем, что это вложенные хосты
    geek:     # задаём имя группы, может быть любым
      hosts: #
        Localhost:  # указываем ip или FQDN
        172.16.234.10:  # это объекты и после них надо делать двоеточие!!!
          ansible_user: "geek"