---
- name: install and start mysql-server
  block:
    - name: install mysql-server
      apt:
        name: mysql-server
        state: present
      become: true

    - name: start mysql
      service:
        name: mysql
        state: started
        enabled: yes
      become: true